title: energy-generation
hero_image: images/banner.png
description: energy-generation description
version: 4
listed: false
copyedit: false
last_tested: "2020-09-16"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
