title: Energy generation
hero_image: images/banner.png
description: Create a program to input real data on the range of natural resources used by various countries to generate electricity. Then compare the results using an animated data visualisation.
version: 4
listed: false
copyedit: false
last_tested: "2020-09-16"
steps:
  - title: Introduction
  - title: Duplicate a second graph
  - title: Make a third graph
  - title: Build a pen
  - title: Draw the column
  - title: Create the resource variables
  - title: Share your project
  - title: What next?
