---
title: वीज निर्मिती
hero_image: images/banner.png
description: डेटा व्हिज्युअलायझेशन तयार करा आणि वीज निर्माण करण्यासाठी देशांद्वारे वापरल्या जाणार्‍या नैसर्गिक संसाधनांची तुलना करण्यासाठी वास्तविक डेटा इनपुट करा
version: 4
listed: true
copyedit: false
last_tested: '2020-09-16'
steps:
  - 
    title: परिचय
    completion: engaged
  - 
    title: रंग निवडा
  - 
    title: UK कॉलम जोडा
  - 
    title: तिसरा देश निवडा
  - 
    title: पेन तयार करा
  - 
    title: रिसोर्स व्हेरिएबल्स तयार करा
  - 
    title: तीसरा कॉलम काढा
    completion: internal
  - 
    title: तुमचा प्रोजेक्ट शेअर करा
  - 
    title: पुढे काय?
