---
title: Electricity generation
hero_image: images/banner.png
description: Create a data visualisation and input real data to compare the natural resources used by countries to generate electricity
version: 4
listed: true
copyedit: false
last_tested: "2020-09-16"
steps:
  - 
    title: Introduction
  - 
    title: Pick the colours
  - 
    title: Add a UK column
  - 
    title: Choose a third country
  - 
    title: Build a pen
  - 
    title: Create the resource variables
  - 
    title: Draw the third column
  - 
    title: Share your project
  - 
    title: What next?
